"""
Production Recommendation Tool (synopsis §5.8, §9.6, workflow step 8).

Applies the four-action rule matrix deterministically — reasons are
built from an f-string template using the actual numbers, never
generated by a language model, so a reason can never state something
the data doesn't support.

One documented assumption not fully specified in the synopsis: when
recent sales are zero, days_of_stock is undefined (see inventory.py).
The synopsis says a Declining item can still be discontinued if it has
"clearly excessive stock" even then — but doesn't define "excessive"
without a days-of-stock figure to compare. We fall back to comparing
raw current_stock (units) against the same max(60, 2*lead_time)
threshold the days-based rule uses. This is a reasonable interpretation,
not a spec requirement — flag it if asked to justify it.
"""

from __future__ import annotations

import pandas as pd


def _increase_production_reason(row) -> str:
    return (
        f"Rising demand (trend score {row['trend_score']}) with only "
        f"{row['days_of_stock']:.0f} days of stock against a "
        f"{row['lead_time_days']}-day lead time — restock before demand outpaces supply."
    )


def _plan_for_next_season_reason(row) -> str:
    return (
        f"Strong rising demand (trend score {row['trend_score']}) but stock is adequate "
        f"({row['days_of_stock']:.0f} days) — plan a batch rather than rushing production."
    )


def _discontinue_reason(row, used_unit_fallback: bool) -> str:
    coverage = (
        f"{row['current_stock']:.0f} units on hand with no recent sales"
        if used_unit_fallback
        else f"{row['days_of_stock']:.0f} days of stock"
    )
    return (
        f"Declining demand (trend score {row['trend_score']}) with {coverage} — "
        f"excess coverage on a weakening item."
    )


def _maintain_reason(row) -> str:
    if pd.isna(row["days_of_stock"]):
        return "No recent sales to measure stock coverage — holding at current levels."
    return (
        f"Evidence is stable or not strong enough for a change "
        f"(trend score {row['trend_score']}, direction {row['direction']})."
    )


def compute_recommendations(inventory_df: pd.DataFrame, settings: dict) -> pd.DataFrame:
    rules = settings["production_rules"]
    inc_cfg = rules["increase_production"]
    plan_cfg = rules["plan_for_next_season"]
    disc_cfg = rules["discontinue"]

    df = inventory_df.copy()
    actions = []
    reasons = []

    for _, row in df.iterrows():
        is_rising = row["direction"] == "Rising"
        is_declining = row["direction"] == "Declining"
        stock_unknown = pd.isna(row["days_of_stock"])

        if is_rising and row["trend_score"] >= inc_cfg["min_trend_score"] and not stock_unknown:
            if row["is_low_stock"]:
                actions.append("Increase Production")
                reasons.append(_increase_production_reason(row))
                continue
            elif row["trend_score"] >= plan_cfg["min_trend_score"]:
                actions.append("Plan for Next Season")
                reasons.append(_plan_for_next_season_reason(row))
                continue

        if is_declining and row["trend_score"] <= disc_cfg["max_trend_score"]:
            discontinue_threshold = max(
                disc_cfg["min_days_of_stock_floor"],
                disc_cfg["min_days_of_stock_multiplier"] * row["lead_time_days"],
            )
            if not stock_unknown and row["days_of_stock"] >= discontinue_threshold:
                actions.append("Discontinue")
                reasons.append(_discontinue_reason(row, used_unit_fallback=False))
                continue
            if stock_unknown and row["current_stock"] >= discontinue_threshold:
                actions.append("Discontinue")
                reasons.append(_discontinue_reason(row, used_unit_fallback=True))
                continue

        actions.append("Maintain")
        reasons.append(_maintain_reason(row))

    df["action"] = actions
    df["reason"] = reasons

    # Priority: highest trend score first, item_id as a deterministic tiebreaker.
    df = df.sort_values(["trend_score", "item_id"], ascending=[False, True]).reset_index(drop=True)
    df["priority_rank"] = df.index + 1

    return df
